"""
publish_place.py — publishes build/PowerClicker.rbxlx straight to your existing
place through Roblox Open Cloud, without the Studio "choose an experience"
dialog (the one that fails with "Falha ao buscar").

It publishes into the place you ALREADY have, so your game passes and developer
products keep working. It never creates a new experience.

YOU run this with YOUR key (never paste the key in chat or commit it):

  1. create.roblox.com → Open Cloud → API Keys → your key → Add API System:
       "Place Publishing" (universe-places:write) for your experience
     (the same key used for the images works, just add this permission)
  2. Find the ids: create.roblox.com → your experience
       URL: .../dashboard/creations/experiences/<UNIVERSE_ID>/places/<PLACE_ID>/...
  3. Open build/PowerClicker.rbxlx in Studio and save it (Ctrl+S). Roblox only
     accepts a place file written by Studio, so this step is required after
     every build_place.py run.
  4. In PowerShell:
       $env:ROBLOX_API_KEY  = "<key>"
       $env:ROBLOX_UNIVERSE_ID = "<universe id>"
       $env:ROBLOX_PLACE_ID    = "<place id>"
       python tools/publish_place.py            # live for players
       python tools/publish_place.py --saved    # uploads without going live

Refuses to publish the Studio-mock build (it saves nothing) and refuses a place
file that Studio has not rewritten (Roblox would reject it anyway).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLACE_FILE = os.path.join(ROOT, "build", "PowerClicker.rbxlx")
ENDPOINT = "https://apis.roblox.com/universes/v1/{universe}/places/{place}/versions?versionType={kind}"
# The real build carries DataConfig.StudioBackend = "Real"; the mock build has
# it set to "Mock". Looking for the "Mock" text alone gives a false positive,
# because the kick message explains that setting to the developer.
REAL_MARKER = 'StudioBackend = "Real"'
# Open Cloud only accepts a place file written by Studio. The one build_place.py
# generates is a simplified XML and comes back as "Invalid Content stream";
# Studio always writes this Meta tag, so it tells the two apart.
STUDIO_MARKER = "ExplicitAutoJoints"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--saved", action="store_true", help="upload without making it live")
    parser.add_argument("--file", default=PLACE_FILE, help="place file to publish")
    args = parser.parse_args()

    key = os.environ.get("ROBLOX_API_KEY", "").strip()
    universe = os.environ.get("ROBLOX_UNIVERSE_ID", "").strip()
    place = os.environ.get("ROBLOX_PLACE_ID", "").strip()
    if not key or not universe.isdigit() or not place.isdigit():
        print("Set ROBLOX_API_KEY, ROBLOX_UNIVERSE_ID and ROBLOX_PLACE_ID first (see the top of this file).")
        return 1

    if not os.path.exists(args.file):
        print(f"Place file not found: {args.file}")
        if args.file.lower().endswith(".rbxl"):
            # The binary file can only come from Studio; the build script
            # writes the .rbxlx, never the .rbxl.
            print("That one is saved by Studio: open build/PowerClicker.rbxlx, then")
            print('File > Save to File As, set the type to "Roblox Place (.rbxl)"')
            print("and save it into the build folder as PowerClicker.rbxl.")
        else:
            print("Run: python tools/build_place.py")
        return 1

    with open(args.file, "rb") as handle:
        content = handle.read()

    # The mock build never saves progress; publishing it would be a disaster.
    # A .rbxlx is text, so the setting can be read. A .rbxl is compressed
    # binary: nothing can be read, so only the name is checked and the risk is
    # stated instead of pretending it was verified.
    is_binary = args.file.lower().endswith(".rbxl")
    name = os.path.basename(args.file).lower()
    if is_binary:
        if "mock" in name:
            print("REFUSED: the file name says mock; that build saves nothing.")
            return 1
        print("NOTE: a .rbxl is binary, so the save setting inside it cannot be checked here.")
        print("      Make sure it was saved from PowerClicker.rbxlx, not from the _StudioMock one.")
    elif REAL_MARKER.encode() not in content:
        print("REFUSED: this file uses the Studio mock storage (nothing would be saved).")
        print("Publish build/PowerClicker.rbxlx, built with: python tools/build_place.py")
        return 1

    if not is_binary and STUDIO_MARKER.encode() not in content:
        print("REFUSED: this .rbxlx was generated by tools/build_place.py, and Roblox")
        print("rejects it (\"Invalid Content stream\"). Open it in Studio and save it")
        print("(File > Save to File, Ctrl+S) so Studio rewrites the file, then run again.")
        return 1

    kind = "Saved" if args.saved else "Published"
    url = ENDPOINT.format(universe=universe, place=place, kind=kind)
    # .rbxlx is XML; .rbxl is binary. Sending the wrong pair gets you a 400
    # "Invalid Content stream".
    request = urllib.request.Request(url, data=content, method="POST")
    request.add_header("x-api-key", key)
    request.add_header("Content-Type", "application/octet-stream" if is_binary else "application/xml")

    size_mb = len(content) / (1024 * 1024)
    print(f"Publishing {os.path.basename(args.file)} ({size_mb:.1f} MB) as {kind}...")
    try:
        with urllib.request.urlopen(request, timeout=300) as response:
            body = json.loads(response.read() or b"{}")
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", "replace")[:400]
        print(f"FAILED: HTTP {error.code}: {detail}")
        if error.code in (401, 403):
            print('Check the key has "Place Publishing" (universe-places:write) for THIS experience,')
            print("and that the allowed IP list includes your IP.")
        elif error.code == 400:
            print("Check that the place id belongs to the universe id.")
            if "Content stream" in detail:
                print("Roblox rejected the file itself: open it in Studio and save it (Ctrl+S)")
                print("so Studio rewrites it in its own format, then run this again.")
        return 1
    except OSError as error:
        print(f"FAILED: network: {error}")
        return 1

    version = body.get("versionNumber", "?")
    print(f"ok: version {version} is now {kind.lower()}")
    if kind == "Published":
        print("Players entering new servers get this version; running servers keep the old one.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
