"""
upload_assets.py — uploads the processed art (transparent PNGs) to Roblox via
Open Cloud and writes the ids into src/shared/Config/AssetIds.luau, which the
game already reads (menu/HUD icons, pet portraits, egg images).

YOU run this with YOUR key (never paste the key in chat or commit it):

  1. create.roblox.com → Open Cloud → API Keys → Create API Key
       Access permissions: "Assets" (Read + Write) and
                           "Legacy Assets" → legacy-asset:manage (to resolve image ids)
       Accepted IP: your IP (or 0.0.0.0/0 while uploading, then delete the key)
  2. In a terminal (PowerShell):
       $env:ROBLOX_API_KEY = "<key>"
       $env:ROBLOX_CREATOR_ID = "<your user id>"      # number in your profile URL
       python tools/upload_assets.py                   # --dry-run to only list
     (for a group: $env:ROBLOX_CREATOR_TYPE = "group" and the group id)

Resumable: files already in AssetIds.luau are skipped. Roblox moderates each
image; a rejected one is reported and left out.

Why two ids: Open Cloud uploads a *Decal*. ImageLabel.Image needs the *image*
behind it, so each decal is resolved through the Asset Delivery API.
"""

from __future__ import annotations

import glob
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
import uuid

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_IDS = os.path.join(ROOT, "src", "shared", "Config", "AssetIds.luau")
ASSETS_URL = "https://apis.roblox.com/assets/v1/assets"
OPERATION_URL = "https://apis.roblox.com/assets/v1/operations/{}"
DELIVERY_URL = "https://apis.roblox.com/asset-delivery-api/v1/assetId/{}"
POLL_SECONDS = 2
POLL_ATTEMPTS = 30
DECALS = os.path.join(ROOT, "art", "decal_ids.json")  # uploaded but not yet resolved
RESOLVE_ATTEMPTS = 10  # the image behind a fresh decal can take a few seconds

PATTERNS = [
    "art/final/icons/icon_*.png",
    "art/final/pets/pet_*.png",
    "art/final/eggs/egg_*.png",
    "art/final/branding/badge_vip.png",
    "art/final/branding/logo_title.png",
    "art/monsters/mob_*.png",
    "art/monsters/boss_*.png",
]


def read_ids() -> dict[str, str]:
    if not os.path.exists(ASSET_IDS):
        return {}
    text = open(ASSET_IDS, encoding="utf-8").read()
    text = text[text.find("local AssetIds") :]  # skip the example in the header comment
    return dict(re.findall(r'\[?"?(\w+)"?\]?\s*=\s*"(rbxassetid://\d+)"', text))


def write_ids(ids: dict[str, str]) -> None:
    lines = "\n".join(f'\t{name} = "{value}",' for name, value in sorted(ids.items()))
    body = f"{{\n{lines}\n}}" if ids else "{}"
    source = f'''--!strict
--[[
	AssetIds
	Uploaded image ids by art file name (without extension), e.g.
		icon_power = "rbxassetid://123456789"
	Consumed by Theme.IconImages (icon_*), PetConfig (pet_<Id>) and
	EggConfig (egg_<Id>). A missing entry falls back to the emoji / TODO_ASSET.

	GENERATED by tools/upload_assets.py — safe to edit by hand too.
]]

local AssetIds: {{ [string]: string }} = {body}

return AssetIds
'''
    with open(ASSET_IDS, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)


def call(request: urllib.request.Request) -> dict:
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.loads(response.read() or b"{}")
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", "replace")[:300]
        raise RuntimeError(f"HTTP {error.code}: {detail}") from None
    except OSError as error:  # timeout, DNS, dropped connection
        raise RuntimeError(f"network: {error}") from None


def upload(path: str, key: str, creator: dict) -> str:
    name = os.path.splitext(os.path.basename(path))[0]
    meta = {
        "assetType": "Decal",
        "displayName": f"PowerClicker {name}",
        "description": "Power Clicker UI art",
        "creationContext": {"creator": creator},
    }
    boundary = uuid.uuid4().hex
    with open(path, "rb") as handle:
        content = handle.read()
    body = b"".join(
        [
            f"--{boundary}\r\nContent-Disposition: form-data; name=\"request\"\r\n\r\n".encode(),
            json.dumps(meta).encode(),
            f"\r\n--{boundary}\r\nContent-Disposition: form-data; name=\"fileContent\"; filename=\"{name}.png\"\r\n"
            "Content-Type: image/png\r\n\r\n".encode(),
            content,
            f"\r\n--{boundary}--\r\n".encode(),
        ]
    )
    request = urllib.request.Request(ASSETS_URL, data=body, method="POST")
    request.add_header("x-api-key", key)
    request.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    operation = call(request)
    operation_id = operation.get("operationId") or operation.get("path", "").split("/")[-1]
    for _ in range(POLL_ATTEMPTS):
        if operation.get("done"):
            break
        time.sleep(POLL_SECONDS)
        poll = urllib.request.Request(OPERATION_URL.format(operation_id))
        poll.add_header("x-api-key", key)
        operation = call(poll)
    if not operation.get("done"):
        raise RuntimeError("upload still processing; run again later")
    if "error" in operation:
        raise RuntimeError(f"rejected: {operation['error']}")
    asset_id = (operation.get("response") or {}).get("assetId")
    if not asset_id:
        raise RuntimeError(f"no assetId in {operation}")
    return str(asset_id)


def resolve_image(decal_id: str, key: str) -> str | None:
    """Decal → image id (the decal's XML points at the image asset)."""
    for _ in range(RESOLVE_ATTEMPTS):
        try:
            request = urllib.request.Request(DELIVERY_URL.format(decal_id))
            request.add_header("x-api-key", key)
            location = call(request).get("location")
            if location:
                with urllib.request.urlopen(location, timeout=60) as response:
                    xml = response.read().decode("utf-8", "replace")
                match = re.search(r"asset/?\?id=(\d+)", xml)
                if match:
                    return match.group(1)
        except (RuntimeError, OSError):
            pass  # retried below
        time.sleep(POLL_SECONDS)
    return None


def main() -> int:
    dry_run = "--dry-run" in sys.argv
    files: list[str] = []
    for pattern in PATTERNS:
        files += sorted(glob.glob(os.path.join(ROOT, pattern)))
    ids = read_ids()
    pending = [f for f in files if os.path.splitext(os.path.basename(f))[0] not in ids]
    print(f"{len(files)} images, {len(ids)} already uploaded, {len(pending)} to go")
    if dry_run:
        for path in pending:
            print("  would upload", os.path.relpath(path, ROOT))
        return 0

    key = os.environ.get("ROBLOX_API_KEY", "").strip()
    creator_id = os.environ.get("ROBLOX_CREATOR_ID", "").strip()
    creator_type = os.environ.get("ROBLOX_CREATOR_TYPE", "user").strip().lower()
    if not key or not creator_id.isdigit():
        print("Set ROBLOX_API_KEY and ROBLOX_CREATOR_ID first (see the top of this file).")
        return 1
    creator = {"groupId": creator_id} if creator_type == "group" else {"userId": creator_id}

    decals: dict[str, str] = json.load(open(DECALS)) if os.path.exists(DECALS) else {}
    failures = 0
    for path in pending:
        name = os.path.splitext(os.path.basename(path))[0]
        try:
            decal_id = decals.get(name)  # never upload the same file twice
            if not decal_id:
                decal_id = upload(path, key, creator)
                decals[name] = decal_id
                with open(DECALS, "w") as handle:
                    json.dump(decals, handle, indent=1)
            image_id = resolve_image(decal_id, key)
            if not image_id:
                raise RuntimeError(f"uploaded (decal {decal_id}) but the image id could not be resolved yet; run again")
            ids[name] = f"rbxassetid://{image_id}"
            write_ids(ids)  # save after each one so a crash loses nothing
            print(f"ok   {name} -> {image_id}")
        except (RuntimeError, OSError) as error:
            failures += 1
            print(f"FAIL {name}: {error}")
    print(f"done: {len(ids)} ids in {os.path.relpath(ASSET_IDS, ROOT)}, {failures} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
